# This is a basic workflow to help you get started with Actions

name: Staging to MyGet

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1.0.2
        with:
          nuget-api-key: ${{ secrets.MYGETAPI }}
          nuget-version: 'latest'
        env:  
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'


      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        env:
          working-directory: MetaMomentum/
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

#      - name: Nuget Add Umbraco Prerelease Source
#        run: dotnet nuget add source https://www.myget.org/F/umbracoprereleases/api/v3/index.json --name "Umbraco Prereleases" 

      - name: Run Nuget restore
        run: nuget restore metamomentum.sln

      - name: Copy lucene analyser
        run: |
          $src = "C:\Users\runneradmin\.nuget\packages\lucene.net\4.8.0-beta00014\analyzers\dotnet\cs"
          $dest = "C:\Users\runneradmin\.nuget\packages\lucene.net\3.0.3\analyzers\dotnet\cs"
          if (!(Test-Path -Path $dest)) {
            New-Item -ItemType directory -Path $dest
          }
          Copy-Item -Path $src\*.dll -Destination $dest 

      - name: build
        run: msbuild 
        working-directory: MetaMomentum.Core/

      - name: build
        run: msbuild 
        working-directory: MetaMomentum/

#      - name: Nuget Pack
#        working-directory: MetaMomentum/
#        run: dotnet pack --version-suffix "-dev"
      
      - name: Publish the package to GitHub packages
        working-directory: MetaMomentum/
        run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.MYGETAPI }} --source https://www.myget.org/F/digital-momentum/api/v2/package
        
        
        
      - name: Publish MetaMomentum to MyGet
        working-directory: MetaMomentum/
        run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.MYGETAPI }} --source https://www.myget.org/F/digital-momentum/api/v2/package  

      - name: Publish MetaMomentum.core to MyGet
        working-directory: MetaMomentum.Core/
        run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.MYGETAPI }} --source https://www.myget.org/F/digital-momentum/api/v2/package